compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  zero_optimization:
    stage: 3                       # ZeRO-3 parameter sharding
    offload_param:
      device: cpu                 # offload parameter shards to CPU
      pin_memory: true
    offload_optimizer:
      device: cpu                 # offload optimizer states to CPU
      pin_memory: true
    contiguous_gradients: true    # fuse gradient comms
  activation_checkpointing:
    partition_activations: true   # enable activation checkpointing
    contiguous_memory_optimization: true
main_training_function: main
mixed_precision: fp16
num_machines: 1
machine_rank: 0
num_processes: 6                  # one per GPU
use_cpu: false
