compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  # Nonaktifkan ZeRO (data-parallel state sharding)
  zero_optimization:
    stage: 0

  # Tensor parallelism: pecah setiap operasi layer ke 2 GPU
  tensor_parallel:
    tp_size: 2

  # Pipeline parallelism: pecah model menjadi 3 stage
  pipeline_parallel:
    pp_size: 3

  # Activation checkpointing untuk menghemat memori
  activation_checkpointing:
    partition_activations: true
    contiguous_memory_optimization: true

main_training_function: main
mixed_precision: fp16

# total proses = tp_size * pp_size = 2 * 3 = 6
num_machines: 1
machine_rank: 0
num_processes: 6
use_cpu: false
